<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SKAR1201135" ignored="0" name="Default test" tests="2" failures="0" timestamp="2020-03-26T15:21:06 BRT" time="14.678" errors="0">
  <testcase name="@AfterMethod finalizaTest" time="0.004" classname="br.com.rsinet.hub.tdd.test.RealizarLogin">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at br.com.rsinet.hub.tdd.utils.ConfiguraReport.reportStatus(ConfiguraReport.java:37)
at br.com.rsinet.hub.tdd.test.RealizarLogin.finalizaTest(RealizarLogin.java:81)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:695)
at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:671)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:655)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @AfterMethod finalizaTest -->
  <testcase name="@BeforeMethod Inicializar" time="-1.585246866949E9" classname="br.com.rsinet.hub.tdd.test.RealizarLogin">
    <skipped/>
  </testcase> <!-- @BeforeMethod Inicializar -->
  <testcase name="@AfterMethod finalizaTest" time="-1.585246866956E9" classname="br.com.rsinet.hub.tdd.test.RealizarLogin">
    <skipped/>
  </testcase> <!-- @AfterMethod finalizaTest -->
  <testcase name="realizarLoginFalha" time="2.192" classname="br.com.rsinet.hub.tdd.test.RealizarLogin"/>
  <testcase name="realizarLoginSucesso" time="0.0" classname="br.com.rsinet.hub.tdd.test.RealizarLogin">
    <skipped/>
  </testcase> <!-- realizarLoginSucesso -->
</testsuite> <!-- Default test -->
